# Generated by Django 2.2.4 on 2019-09-25 19:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intranet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('titulo', models.CharField(max_length=120)),
                ('descripcion', models.CharField(max_length=250)),
                ('contenido', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='intranet/imgpost')),
                ('fecIns', models.DateTimeField(auto_now_add=True)),
                ('fecUpd', models.DateTimeField(auto_now=True)),
                ('usuIns', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_usu_ins_publicacion', to=settings.AUTH_USER_MODEL)),
                ('usuUpd', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_usu_upd_publicacion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documento', models.FileField(upload_to='intranet/docs')),
                ('fecIns', models.DateTimeField(auto_now_add=True)),
                ('fecUpd', models.DateTimeField(auto_now=True)),
                ('publicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_publicacion_documento', to='intranet.Publicacion')),
                ('usuIns', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='usu_ins_publicacion', to=settings.AUTH_USER_MODEL)),
                ('usuUpd', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='usu_upd_publicacion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
