# Generated by Django 2.2.4 on 2019-10-02 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0003_auto_20190926_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
