# Generated by Django 2.2.4 on 2019-10-31 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0004_publicacion_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicacion',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='intranet/img/post'),
        ),
    ]
