# Generated by Django 2.2.4 on 2020-08-20 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0005_auto_20191031_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicacion',
            name='cumpleanho',
            field=models.BooleanField(default=False, verbose_name='Sección Cumpleaños'),
        ),
    ]
