# Generated by Django 2.2.4 on 2019-11-01 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0003_cargo_dependencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dependencia',
            name='dependencia_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rh.Dependencia'),
        ),
    ]
