# Generated by Django 2.2.4 on 2020-02-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rh', '0004_auto_20191101_1240'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interno',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependencia', models.CharField(max_length=250)),
                ('responsable', models.CharField(blank=True, max_length=250, null=True)),
                ('extension', models.IntegerField()),
                ('sede', models.CharField(choices=[('CEN', 'CENTRAL'), ('VTA', 'VILLETA'), ('VMI', 'VALLEMI')], default='CEN', max_length=3)),
            ],
        ),
    ]
