# Generated by Django 2.2.4 on 2019-09-12 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='es_admin',
        ),
        migrations.AddField(
            model_name='perfil',
            name='legajo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
