# Generated by Django 2.2.4 on 2019-09-23 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_auto_20190912_1334'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='sede',
            field=models.CharField(choices=[('CEN', 'CENTRAL'), ('VTA', 'VILLETA'), ('VMI', 'VALLEMI')], default='CEN', max_length=3),
        ),
    ]
