# Generated by Django 2.2.4 on 2019-10-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_auto_20191017_0825'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cargo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominacion', models.CharField(max_length=100)),
                ('creacion', models.DateTimeField(auto_now_add=True)),
                ('modificacion', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='perfil',
            name='tip_empleado',
            field=models.CharField(blank=True, choices=[('PER', 'PERMANENTE'), ('CON', 'CONTRATADO'), ('TER', 'TERCERIZADO')], max_length=3, null=True),
        ),
    ]
