# Generated by Django 2.2.4 on 2019-10-17 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_auto_20191017_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cargo',
            name='denominacion',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
