# Generated by Django 2.2.4 on 2019-10-17 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_auto_20191017_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_cargo_perfil', to='usuarios.Cargo'),
        ),
    ]
