# Generated by Django 2.2.4 on 2019-10-17 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_dependencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='dependecia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_dependencia_empleado_perfil', to='usuarios.Dependencia'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_cargo_empleado_perfil', to='usuarios.Cargo'),
        ),
    ]
