# Generated by Django 2.2.4 on 2019-10-21 17:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_auto_20191017_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='dependencia',
            name='dependencia_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_dependencia_padre', to='usuarios.Dependencia'),
        ),
    ]
