# Generated by Django 2.2.4 on 2019-10-22 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0010_dependencia_dependencia_padre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='fec_nombramiento',
            new_name='fec_vinculacion',
        ),
    ]
