# Generated by Django 2.2.4 on 2019-10-22 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0011_auto_20191022_0846'),
    ]

    operations = [
        migrations.AddField(
            model_name='cargo',
            name='estado',
            field=models.CharField(choices=[('A', 'ACTIVO'), ('I', 'INACTIVO')], default='A', max_length=1),
        ),
        migrations.AddField(
            model_name='dependencia',
            name='estado',
            field=models.CharField(choices=[('A', 'ACTIVO'), ('I', 'INACTIVO')], default='A', max_length=1),
        ),
    ]
