# Generated by Django 2.2.4 on 2019-10-22 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0012_auto_20191022_0857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perfil',
            old_name='dependecia',
            new_name='dependencia',
        ),
    ]
