# Generated by Django 2.2.4 on 2019-10-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0014_perfil_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Hombre'), ('F', 'Mujer')], max_length=1, null=True),
        ),
    ]
