# Generated by Django 2.2.4 on 2019-10-30 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0016_auto_20191030_0853'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_ciudad_perfil', to='usuarios.Ciudad'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_departamento_perfil', to='usuarios.Departamento'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='documento_identidad',
            field=models.FileField(blank=True, null=True, upload_to='usuarios/docs/ci'),
        ),
        migrations.AddField(
            model_name='perfil',
            name='nacionalidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_nacionalidad_perfil', to='usuarios.Nacionalidad'),
        ),
    ]
