# Generated by Django 2.2.4 on 2019-10-31 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0017_auto_20191030_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ciudad',
            name='departamento',
        ),
        migrations.RemoveField(
            model_name='departamento',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='dependencia',
            name='dependencia_padre',
        ),
        migrations.AlterField(
            model_name='perfil',
            name='cargo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_cargo_empleado_perfil', to='rh.Cargo'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='ciudad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_ciudad_perfil', to='bs.Ciudad'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_departamento_perfil', to='bs.Departamento'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='dependencia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_dependencia_empleado_perfil', to='rh.Dependencia'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='documento_identidad',
            field=models.FileField(blank=True, null=True, upload_to='usuarios/doc/ci'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='estado_civil',
            field=models.CharField(choices=[('SO', 'Soltero/a'), ('CA', 'Casado/a'), ('VI', 'Viudo/a'), ('DI', 'Divorciado/a'), ('DE', 'Desconocido/a')], default='DE', max_length=2),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='usuarios/img/fotos'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='nacionalidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_nacionalidad_perfil', to='bs.Nacionalidad'),
        ),
        
    ]
