# Generated by Django 2.2.4 on 2019-10-31 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0018_auto_20191031_1122'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cargo',
        ),
        migrations.DeleteModel(
            name='Ciudad',
        ),
        migrations.DeleteModel(
            name='Departamento',
        ),
        migrations.DeleteModel(
            name='Dependencia',
        ),
        migrations.DeleteModel(
            name='Nacionalidad',
        ),
        migrations.DeleteModel(
            name='Pais',
        ),
    ]
