# Generated by Django 2.2.4 on 2019-10-31 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0019_auto_20191031_1126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='cargo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='dependencia',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
