# Generated by Django 2.2.4 on 2019-11-01 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0022_auto_20191101_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='departamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ciudad2', to='bs.Departamento'),
        ),
    ]
