# Generated by Django 2.2.4 on 2020-02-04 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0024_auto_20191101_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='estado_civil',
            field=models.CharField(choices=[('SO', 'Soltero/a'), ('CA', 'Casado/a'), ('VI', 'Viudo/a'), ('DI', 'Divorciado/a'), ('SE', 'Separado/a'), ('DE', 'Desconocido/a')], default='DE', max_length=2),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='tip_empleado',
            field=models.CharField(blank=True, choices=[('PER', 'PERMANENTE'), ('CON', 'CONTRATADO'), ('COM', 'COMISIONADO')], max_length=3, null=True),
        ),
    ]
